'use client'
import { Button } from '@/components/ui/button'
import { Download } from 'lucide-react'
import React from 'react'

type Props = {
    title: string;
    createdAt: string;
    summaryText: string;
    fileName: string;
}
export default function DownloadSummary(
    { title, createdAt, summaryText, fileName }: Props
) {
    const handelDownload = () => {
        const summaryContent = `#${title}
        Generated Summary
        Generated Summary on: ${new Date(createdAt).toLocaleDateString()}
        
        ${summaryText}
        Original File: ${fileName}
        Generated by Briefly`;
        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a')
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`
        document.body.appendChild(link)
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }
    return (
        <div className=''>
            <Button variant={'ghost'} className='text-rose-600 bg-rose-100 rounded hover:bg-rose-200 hover:text-rose-600 cursor-pointer' onClick={handelDownload}>

                <Download className='h-4 w-4' />
            Download Summary
            </Button>
        </div>
    )
}
